export const errorCodes = Object.freeze({
  UNKNOWN: "UNKNOWN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TASK_LOCKED: "TASK_LOCKED",
  ETAG_MISMATCH: "ETAG_MISMATCH",
  REPO_LOCKED: "REPO_LOCKED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
});
